apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
    name: positions.whu.edu.cn
spec:
    group: whu.edu.cn
    versions:
        - name: v1
          served: true
          storage: true
          schema:
            openAPIV3Schema:
                type: object
                properties:
                    spec:
                        type: object
                        properties:
                            country:
                                type: string
                            province:
                                type: string
    scope: Namespaced
    names:
        plural: positions
        singular: position
        kind: Position
        shortNames:
            - pos
