apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: students.whu.edu.cn
spec:
  group: whu.edu.cn
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                school:
                    type: string
  scope: Namespaced
  names:
    plural: students
    singular: student
    kind: Student
    shortNames:
      - stu